In [4]:
## Part 2
#For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](https://www2.census.gov/programs-surveys/popest/technical-documentation/file-layouts/2010-2015/co-est2015-alldata.pdf) for a description of the variable names.
#The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.
import pandas as pd

census_df = pd.read_csv('data/census.csv')
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [2]:
### Question 5
#**Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)
#*This function should return a single string value.*
def answer_five():
    group_state = census_df.groupby(["STNAME"], sort=False).sum()
    state = group_state["COUNTY"].idxmax()

    return state

answer_five()

'Texas'

In [3]:
### Question 6
#**Only looking at the three most populous counties for each state**, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.
#*This function should return a list of string values.*
def answer_six():
    new_df = census_df[census_df['SUMLEV'] == 50]

    #Taking the three most populous counties for each state
    mpc = new_df.sort_values('CENSUS2010POP', ascending=False).groupby('STNAME').head(3)

    #Taking the three most populous states
    mpc = mpc.groupby('STNAME').sum().sort_values('CENSUS2010POP', ascending=False).head(3)

    #Converting results to a list
    mpc = mpc.index.tolist()

    return mpc

answer_six()

['California', 'Texas', 'Illinois']

In [3]:
### Question 7
#**Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

#e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

#*This function should return a single string value.*
def answer_seven():
    new_df = census_df[census_df['SUMLEV'] == 50]

    #Creating dataframe with the necessary data
    new_df = new_df[
        ['CTYNAME', 'POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014',
         'POPESTIMATE2015']]

    #Verify the maxDif of the columns
    new_df["MaxDiff"] = abs(new_df.max(axis=1) - new_df.min(axis=1))
    most_change = new_df.sort_values(by=["MaxDiff"], ascending=False)

    return most_change.iloc[0][0]

answer_seven()

'Harris County'

In [5]:
### Question 8
#In this datafile, the United States is broken up into four regions using the "REGION" column.

#**Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

#*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*
def answer_eight():
    new_df = census_df[census_df['SUMLEV'] == 50]
    new_df = new_df[(new_df['REGION'] == 1) | (new_df['REGION'] == 2)]
    new_df = new_df[new_df['CTYNAME'].str.startswith('Washington')]
    new_df = new_df[new_df['POPESTIMATE2015'] > new_df['POPESTIMATE2014']]
    new_df = new_df[['STNAME', 'CTYNAME']]

    return new_df

answer_eight()

            STNAME            CTYNAME
896           Iowa  Washington County
1419     Minnesota  Washington County
2345  Pennsylvania  Washington County
2355  Rhode Island  Washington County
3163     Wisconsin  Washington County